name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:15.0.0  # container oficial com Cypress 15 + Node incluído

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
